### ISSUE TITLE
系统的好像怎么也无法调用到？

### ISSUE THREAD

**Issue by isolet** [liberize/alfred-dict-workflow#1]
清空了缓存也不行……除了系统自带词典其它都没有问题。

**Comment by itomg** [comment]
##### OS X 10.9.5 我的没有“牛津英汉汉英词典”，如下改动之后可以使用 :ok_hand: 
![2015-10-22 16 14 59](https://cloud.githubusercontent.com/assets/3071050/10660374/18e84bac-78d9-11e5-9908-69c4e7899c95.png)
###### cc :config
```bash
## 『show in finder』找到文件
/Users/[username]/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.1BD2F640-E5C8-4450-B0FC-118691044088/cndict/oxford.py

## line 22
dict_name = '牛津英汉汉英词典'
## change to 
dict_name = 'Oxford Chinese Dictionary'
```
###### cc :update

**Comment by liberize** [comment]
这个地方我写的时候就在想会不会有的系统版本里面是英文，然而我手头只有 yosemite 供测试，所以就没有改。
这个 issue 提出时的代码跟现在有很大不同，不确定是不是这个原因。
Anyway, 我把这个地方 fix 之后，把这个 issue close 掉吧。

**Comment by itomg** [comment]
@liberize v2.2.2 已测，没有问题 :ok_hand:
