### ISSUE TITLE
考虑给bing翻译来一发吗？

### ISSUE THREAD

**Issue by qqli007** [liberize/alfred-dict-workflow#10]
可以加个bing在线翻译的功能吗

**Comment by liberize** [comment]
翻译涉及的修改比较多，甚至可以写一个新的 workflow。
目前以修复 bug 为主，还有几个 feature 要加上，所以短期内没有加翻译的打算。

**Comment by mickeyandkaka** [comment]
bing 的翻译事实上是有api的。但是有次数限制。
对于api 需要每个人一个特定的token。
我认为可以考虑下，毕竟bing翻译的质量还是比较高的。

**Comment by fanglei-hangzhou** [comment]
问下发音怎么发的

**Comment by liberize** [comment]
@fanglei-hangzhou 改配置文件 keymap -> none，看下 readme
