### ISSUE TITLE
使用ctrl/alt/cmd+enter等快捷键快速切换无法重新弹出alfred窗口

### ISSUE THREAD

**Issue by latte-z** [liberize/alfred-dict-workflow#11]
症状是使用组合键+enter的时候无法自动弹出新的alfred窗口
默认词典的open/say功能正常使用
当前python命令默认的系统自带版本被我换成了brew安装的2.7.12，不知道是否是这个原因？
修改快捷键&update测试也无法解决

update
在debug模式下，出现提示：

[2016-07-09 11:15:08][input.scriptfilter] Processing output of 'action.script' with arg 'about @ nj'
[2016-07-09 11:15:09][ERROR: action.script] 31:39: syntax error: “°∞"°±”不能跟在“±Í ∂∑˚”之后。 (-2740)
[2016-07-09 11:15:09][action.script] Processing output of 'output.notification' with arg ''

**Comment by liberize** [comment]
试试在终端执行：
osascript -e 'tell application "Alfred 3" to search "about @ nj"'
如果 alfred 版本是 2.x，请换成 Alfred 2.

**Comment by latte-z** [comment]
我的版本是3，这条applescript可以正常执行，请问还需要做什么工作？

**Comment by liberize** [comment]
看来是版本检测有问题，麻烦看一下你的 workflow 路径。
在 workflow 管理界面选中插件，右键可以在 finder 中打开。

**Comment by latte-z** [comment]
那感觉可能是因为我自己设置了同步文件夹的原因，workflow的路径已经被我改到Onedrive里同步了
/Users/Ryan/OneDrive/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.65A49946-52B0-4697-A8CA-C48D6A6B2B14

**Comment by liberize** [comment]
麻烦 clone 最新代码测试一下。
```bash
git clone https://github.com/liberize/alfred-dict-workflow
cd alfred-dict-workflow
make
make install
```

**Comment by latte-z** [comment]
感谢！问题已解决！
