### ISSUE TITLE
国外访问bing词典的问题

### ISSUE THREAD

**Issue by finalion** [liberize/alfred-dict-workflow#14]
我在写anki查词插件的时候也遇到这个问题，国外访问会获取不到。

目前我的方式是先获取词典查询首页，保存一个cookie，然后携带cookie再进行查词。 

https://github.com/finalion/WordQuery/blob/master/wquery/service/bing.py

**Comment by liberize** [comment]
我刚才测了一下，确实存在这种问题
然后我发现加上 mkt=zh-cn 参数就可以了，不需要 cookie

**Comment by liberize** [comment]
我开 vpn 测了一下，确实有这个问题，
不过我发现不需要 cookie，加上 mkt=zh-cn 就可以了
http://www.bing.com/dict/search?q=test&mkt=zh-cn
（本来以为搞错了，删了一条评论，重发一遍）

**Comment by finalion** [comment]
谢谢！刚才看到评论了，试了下，确实如此。我也改一下
