### ISSUE TITLE
Can not work in nj

### ISSUE THREAD

**Issue by zjzsliyang** [liberize/alfred-dict-workflow#15]
Can not work in nj, Oxford in High Sierra
the error: Word "hello" doesn't exist in dict "nj".
Only I press the return key and in the Dictionary app can work.

**Comment by tonymoxtra** [comment]
Same here.

**Comment by nmchgx** [comment]
Same.

**Comment by haotian-wu** [comment]
Same.

**Comment by zhaochunqi** [comment]
Same here.

**Comment by kevenp** [comment]
same

**Comment by TerranTian** [comment]
+1

**Comment by villadora** [comment]
+1 is that caused by os upgrade?

**Comment by codeyuan** [comment]
+1

**Comment by brallow** [comment]
Same here. high sierra

**Comment by pen1120** [comment]
Same here. high sierra
But it works in `./systemdict -t html -d 牛津英汉汉英词典 test`

**Comment by liberize** [comment]
The output html format changes after every os update. I usually don't upgrade my os until it's neccessary. Sorry.

**Comment by liberize** [comment]
May be fixed, please update and try it out.

**Comment by xiehuc** [comment]
where did systemdict code come from?
consider using another approch?
https://apple.stackexchange.com/questions/90040/look-up-a-word-in-dictionary-app-in-terminal
i found this. a sample swift code runs fast, and much simple than systemdict output. i think.

i could make a pr some time later

**Comment by liberize** [comment]
https://github.com/liberize/DictionaryKit <https://github.com/liberize/DictionaryKit>

https://github.com/liberize/alfred-dict-workflow/commit/5f28b9c2b93b0c5b71ddf1ceaec298e0c07d456b <https://github.com/liberize/alfred-dict-workflow/commit/5f28b9c2b93b0c5b71ddf1ceaec298e0c07d456b>

it’s not that simple.

inspect commit history, you’ll find that i used to parse text output (DCSCopyTextDefinition),
but the parsing code was very complicated and hard to maintain.

Parsing xml output is more robust and reliable.
