### ISSUE TITLE
求支持忽略大小写的查词模式，因为发现有些首字母大写的词查不出来

### ISSUE THREAD

**Issue by vincentor** [liberize/alfred-dict-workflow#17]
比如这个词：
Confounding  # 这样查不出
confounding  # 这样就能查的出

具体看看下图：
![record](https://user-images.githubusercontent.com/2193194/42203444-5a8359de-7ed1-11e8-90a4-ae311cf52eb9.gif)

**Comment by liberize** [comment]
最近没时间搞这个了，一堆 bug，high sierra 也不兼容
欢迎提 PR ...
