### ISSUE TITLE
Need rebuild for macOS 10.14 Mojave

### ISSUE THREAD

**Issue by Sean-Lan** [liberize/alfred-dict-workflow#18]
This dict workflow is the best dict workflow I have ever met! Thanks for working on this!

The latest released version (v2.2.4) doesn't work on macOS 10.14 Mojave, the default Oxford dict always returns: `Word Cat doesn't exist in dict nj`.

Download the source code and re-build (i.e., `make`) the alfred workflow will fix this issue.

**Comment by liberize** [comment]
The release page hasn't been updated for quite a while. Will upload a new release sometime later.
