### ISSUE TITLE
Python3.7 兼容问题...

### ISSUE THREAD

**Issue by shenguanjiejie** [liberize/alfred-dict-workflow#20]
我之前系统默认是Python2的,后来我改成了Python3,我用的是3.7,然后就用不了了.
我尝试自己改源码,但是有些问题解决不了,麻烦看一下,你这个workflow是我Alfred最重要的功能,离不开 : )

**Comment by liberize** [comment]
其实，你不用改 python 代码，只要在 Alfred 的 workflow 管理页面，把脚本里面的 python 改成 python2 应该就可以了
![](http://ww1.sinaimg.cn/large/ded9da26gy1g0qibflwj7j20u60qn0x6.jpg)
![](http://ww1.sinaimg.cn/large/ded9da26gy1g0qicr3zp7j20ug0ltq68.jpg)

**Comment by shenguanjiejie** [comment]
谢谢帮助 哈哈

**Comment by shenguanjiejie** [comment]
改成了python2.7 确实可以用了,不过有一个小问题,就是actions用不了,对我来说无所谓,我基本也不用actions.不过如果你觉得有必要的话,可以看情况改.

**Comment by liberize** [comment]
你全部都改了吗？理论上都改了应该是可以的

**Comment by shenguanjiejie** [comment]
我只改了你截图的那个地方 python改成了python2.7 还有哪里可以改?

**Comment by liberize** [comment]
这里面每一个打开看一下，有就改掉
![](http://ww1.sinaimg.cn/large/ded9da26gy1g0qibflwj7j20u60qn0x6.jpg)

**Comment by shenguanjiejie** [comment]
哦哦 这样啊 好的

**Comment by shenguanjiejie** [comment]
可以了 谢谢 : )
