### ISSUE TITLE
希望增加两个选项

### ISSUE THREAD

**Issue by boboweb** [liberize/alfred-dict-workflow#5]
1、默认搜索可以设置，比如我现在用有道；
2、默认不显示第一条结果提示，就是提示用组合键查询的那条。

目前两条我自己改代码完善了，但是还是希望官方能增加，谢谢 :)

**Comment by liberize** [comment]
1. 这只是一个插件，怎么让用户设置没有好办法。
2. 第一条不显示，那就没有音标了，也无法切换、打开 url、发音，所以不能去掉。

**Comment by boboweb** [comment]
嗯，了解，这个插件已经做的非常好了，我非常喜欢。
