### ISSUE TITLE
请问如何设置dict {word} @ yd 为默认搜索方式呢？

### ISSUE THREAD

**Issue by think2011** [liberize/alfred-dict-workflow#6]
因为 dict {word} 有时搜索不到我的内容，所以我得再输入 @ yd。

我该如何默认就是用yd或者bd之类的呢？

谢谢

**Comment by liberize** [comment]
打开 Alfred 的 workflow 管理界面，选择本插件，右边可以看到流程图，可以看到不同的修饰键(ctrl,
alt...)对应不同的分支，双击标有修饰键的线可以修改，交换 yd 和默认的修饰键即可。
手机回复，无法上图，见谅。
2015年7月12日 01:41于 "曾浩" <notifications@github.com>写道：

**Comment by liberize** [comment]
好像弄错了，只能改代码，我明天加上设置默认词典的功能。
2015年7月12日 02:41于 "Paul Lee" <liberize@gmail.com>写道：

**Comment by think2011** [comment]
@liberize 试着改了一下，没有成功，然后我仔细留意了提示文案，知道怎么快速切换了，谢谢！

**Comment by liberize** [comment]
已支持配置默认词典，详见 README

**Comment by think2011** [comment]
太好了 😄
