### ISSUE TITLE
建议在字典源里加上dict.cn

### ISSUE THREAD

**Issue by boboweb** [liberize/alfred-dict-workflow#7]
dict.cn 做的也还是不错了，有些细节比youdao还要好点，建议在字典源里加上

**Comment by liberize** [comment]
加上倒是可以，但是快捷键不够用了
![image](https://cloud.githubusercontent.com/assets/3303478/8636246/6160341c-2889-11e5-9cac-48a5c4052e83.png)

**Comment by liberize** [comment]
dict.cn 和 bing 一样，没有 API

**Comment by liberize** [comment]
海词是取地下的详尽释义还是上面的简洁释义呢？
![image](https://cloud.githubusercontent.com/assets/3303478/8637711/ac53fdfc-28d2-11e5-8887-c09265034fee.png)

**Comment by liberize** [comment]
已支持海词词典，代号为 hc 或 dictcn，请更新到最新版，有问题欢迎反馈。

**Comment by boboweb** [comment]
赞！高效！
