### ISSUE TITLE
Bing 返回的条目不全

### ISSUE THREAD

**Issue by pinggod** [liberize/alfred-dict-workflow#9]
bing 搜索 rad，感觉数据和 bing 有所出入

[在线链接](http://www.bing.com/dict/search?q=rad)：

![](http://i4.tietuku.com/785faa6677f90280.png)

Alfred:

![](http://i4.tietuku.com/4daf7d612bd5c953.png)

**Comment by liberize** [comment]
bing 默认查询的是 wap page (忽略网络释义): http://dict.bing.com.cn/?view=wap&q=rad

`cc :` 选 config，bing 底下的 `wap_page` 修改为 false，然后 update 和 clean 一下，重新查就是解析你上面的那个页面（同样忽略了网络释义）

**Comment by liberize** [comment]
![image](https://cloud.githubusercontent.com/assets/3303478/11832180/9a0d2620-a3f0-11e5-8140-db0559503580.png)

**Comment by pinggod** [comment]
@liberize 

Goog job , thanks!

**Comment by pinggod** [comment]
为什么要忽略网络释义呢？用的时候还是挺重要的，是否有配置项支持网络释义？

**Comment by liberize** [comment]
不同词典网络释义格式比较混乱，后面有空再加吧

**Comment by pinggod** [comment]
:ok_hand:
